language: java

install: skip

before_install:
- sudo apt-get install jq
  - wget -O ~ / codacy -cover-reporter-assembly-latest.jar https://github.com/codacy/codacy-coverage-reporter/releases/ download / 2.0.2 / codacy -cover-reporter-2.0.2 -montaje.jar

  # Instalar golang / dep (https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-use-dep-in-ci)  
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $ GOPATH / bin / dep
after_success:
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml

jdk: openjdk8

script:
  - ./gradlew check
  - ./gradlew build check

